/*#define Z_LEVEL_ARFS_ONE					1
#define Z_LEVEL_ARFS_TWO					2
#define Z_LEVEL_ARFS_THREE					3
#define Z_LEVEL_CENTCOM_ARFS				4
#define Z_LEVEL_EMPTY_ARFS					5
#define Z_LEVEL_ABANDONED_ASTEROID_ARFS		6
#define Z_LEVEL_MINING_ARFS					7
#define Z_LEVEL_MINING_DANGER_ARFS			8
#define Z_LEVEL_RESIDENTIAL_ARFS			9

#define Z_LEVEL_BOTTOM_DECK				Z_LEVEL_ARFS_ONE
#define Z_LEVEL_TOP_DECK				Z_LEVEL_ARFS_THREE
*/
